language: python
python:
  - 3.4
  - 3.3
  - 2.7
script: make coverage
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/incuna_mail'
  matrix:
    - DJANGO_VERSION='django>=1.6,<1.7'
    - DJANGO_VERSION='django>=1.5,<1.6'
    - DJANGO_VERSION='django>=1.4,<1.5'
matrix:
  exclude:
     - env: DJANGO_VERSION='django>=1.4,<1.5'
       python: 3.4
     - env: DJANGO_VERSION='django>=1.4,<1.5'
       python: 3.3
install:
  - psql -c 'CREATE DATABASE incuna_mail' -U postgres;
  - pip install $DJANGO_VERSION
  - pip install -e .
  - pip install -r test_requirements.txt
  - pip install coveralls
after_success:
  coveralls
