language: python
python:
  - 2.7
script: make test
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/incuna_mail'
  matrix:
    - DJANGO_VERSION>=1.6,<1.7
    - DJANGO_VERSION>=1.5,<1.6
    - DJANGO_VERSION>=1.4,<1.5
matrix:
  exclude:
     - env: DJANGO_VERSION>=1.4,<1.5
       python: 3.3 
install:
  - psql -c 'CREATE DATABASE incuna_mail' -U postgres;
  - pip install Django==$DJANGO_VERSION
  - pip install -e .
  - pip install -r test_requirements.txt
  - pip install coveralls
after_success:
  coveralls
