language: python
python:
  - 3.4
  - 3.3
  - 2.7
script: make test
notifications:
  email: false
env:
  matrix:
    - DJANGO_VERSION='django~=1.8.5'
install:
  - pip install $DJANGO_VERSION
  - pip install -e .
  - pip install -r test_requirements.txt
  - pip install coveralls
after_success:
  coveralls
